### ISSUE TITLE
How to expend pubkey from 512bit to 3072bit?

### ISSUE THREAD

**Issue by baryon** [scrypt-sv/rabin#10]
We have a paper at 
https://nchain.com/app/uploads/2018/09/Rabin-Signatures-in-Bitcoin-Cash-v2.pdf

its point
> To ensure a 128-bit security level a Rabin (or RSA) public key ݊ must be of the order 3072-
bits. This is notably larger than the 256-bits needed for a similar key in elliptic curve
cryptography. The digest of the hash function ܪ and the ܵ part of the signature must
therefore also be of the order 3072-bits. 

the js code using 512bit (64bytes), How to expend to 3072bit?

**Comment by xhliu** [comment]
https://github.com/sCrypt-Inc/rabin/pull/11
