### ISSUE TITLE
qstring and pstring

### ISSUE THREAD

**Issue by kehiy** [scrypt-sv/rabin#19]
Hi,
In go implementation, how to generate pstring and qstring???

**Comment by gitzhou** [comment]
migrate from https://github.com/sCrypt-Inc/rabin/blob/master/src/rabin.ts#L146-L150 is an option

**Comment by kehiy** [comment]
but I'm in golang version.

**Comment by xhliu** [comment]
@gitzhou https://github.com/sCrypt-Inc/rabin/tree/master/golang

**Comment by gitzhou** [comment]
We will migrate the code to golang later, stay tuned

**Comment by kehiy** [comment]
thanks
